<?php
class BBaseOptimize extends UWorkletBehavior
{
	public function beforeBuild()
	{
		$all = asma()->publish(app()->basePath .DS. 'assets' .DS. 'all.css');
		cs()->registerCssFile($all);
		$scriptMap = array(
			'base.dialog.css' => $all,
			'base.googleMap.css' => $all,
			'base.language.css' => $all,
			'deal.all.css' => $all,
			'deal.allFilter.css' => $all,
			'deal.coupons.css' => $all,
			'deal.media.list.css' => $all,
			'deal.price.dialog.css' => $all,
			'deal.print.css' => $all,
			'deal.recent.css' => $all,
			'deal.side.css' => $all,
			'deal.slideshow.css' => $all,
			'deal.stats.css' => $all,
			'deal.status.css' => $all,
			'deal.subscribe.css' => $all,
			'deal.timeLeft.css' => $all,
			'deal.view.css' => $all,
			'location.select.css' => $all,
			'payment.cart.css' => $all,
			'payment.menu.css' => $all,
			'payment.success.css' => $all,
			'user.menu.css' => $all,
		);
		cs()->scriptMap = CMap::mergeArray(cs()->scriptMap,$scriptMap);
		$all = asma()->publish(app()->basePath .DS. 'assets' .DS. 'all.js');
		cs()->registerScriptFile($all);
		$scriptMap = array(
			'jquery.scrollTo-min.js' => $all,
			'jquery.uniprogy.binds.js' => $all,
			'jquery.uniprogy.js' => $all,
			'base.googleMap.js' => $all,
			'base.topMenu.js' => $all,
			'deal.all.js' => $all,
			'deal.loc.js' => $all,
			'deal.purchase.js' => $all,
			'deal.slideshow.js' => $all,
			'deal.status.js' => $all,
			'deal.timeLeft.js' => $all,
			'jquery.timers.js' => $all,
			'jquery.uniprogy.loc.js' => $all,
			'location.select.js' => $all,
			'payment.cart.js' => $all,
			'subscription.admin.updateNewsletter.js' => $all,
		);
		cs()->scriptMap = CMap::mergeArray(cs()->scriptMap,$scriptMap);

		Yii::addCustomClasses(array('MAdminLoginForm' => app()->basePath.'/modules/admin/models/MAdminLoginForm.php',
'MAdminToolsMessageModel' => app()->basePath.'/modules/admin/models/MAdminToolsMessageModel.php',
'MAdminToolsThemeModel' => app()->basePath.'/modules/admin/models/MAdminToolsThemeModel.php',
'MCitymanagerLevelForm' => app()->basePath.'/modules/agent/models/MCitymanagerLevelForm.php',
'MCitymanagerList' => app()->basePath.'/modules/agent/models/MCitymanagerList.php',
'MCitymanagerLoginForm' => app()->basePath.'/modules/agent/models/MCitymanagerLoginForm.php',
'UApiWorklet' => app()->basePath.'/modules/api/components/UApiWorklet.php',
'MBaseAppParamsForm' => app()->basePath.'/modules/base/models/MBaseAppParamsForm.php',
'MBaseCaptchaForm' => app()->basePath.'/modules/base/models/MBaseCaptchaForm.php',
'MBaseContactForm' => app()->basePath.'/modules/base/models/MBaseContactForm.php',
'MBaseFollowForm' => app()->basePath.'/modules/base/models/MBaseFollowForm.php',
'MBaseLanguageForm' => app()->basePath.'/modules/base/models/MBaseLanguageForm.php',
'MDealAllFilterForm' => app()->basePath.'/modules/deal/models/MDealAllFilterForm.php',
'MDealAllListModel' => app()->basePath.'/modules/deal/models/MDealAllListModel.php',
'MDealBackgroundForm' => app()->basePath.'/modules/deal/models/MDealBackgroundForm.php',
'MDealBackgroundImageForm' => app()->basePath.'/modules/deal/models/MDealBackgroundImageForm.php',
'MDealCategoryForm' => app()->basePath.'/modules/deal/models/MDealCategoryForm.php',
'MDealCouponListModel' => app()->basePath.'/modules/deal/models/MDealCouponListModel.php',
'MDealForm' => app()->basePath.'/modules/deal/models/MDealForm.php',
'MDealGeneralForm' => app()->basePath.'/modules/deal/models/MDealGeneralForm.php',
'MDealImageForm' => app()->basePath.'/modules/deal/models/MDealImageForm.php',
'MDealInfoForm' => app()->basePath.'/modules/deal/models/MDealInfoForm.php',
'MDealListModel' => app()->basePath.'/modules/deal/models/MDealListModel.php',
'MDealMediaDescriptionForm' => app()->basePath.'/modules/deal/models/MDealMediaDescriptionForm.php',
'MDealMediaForm' => app()->basePath.'/modules/deal/models/MDealMediaForm.php',
'MDealNameForm' => app()->basePath.'/modules/deal/models/MDealNameForm.php',
'MDealOrderList' => app()->basePath.'/modules/deal/models/MDealOrderList.php',
'MDealParamsForm' => app()->basePath.'/modules/deal/models/MDealParamsForm.php',
'MDealPartnerForm' => app()->basePath.'/modules/deal/models/MDealPartnerForm.php',
'MDealPaymentModel' => app()->basePath.'/modules/deal/models/MDealPaymentModel.php',
'MDealPaymentOptionsForm' => app()->basePath.'/modules/deal/models/MDealPaymentOptionsForm.php',
'MDealPaymentOrderModel' => app()->basePath.'/modules/deal/models/MDealPaymentOrderModel.php',
'MDealPriceForm' => app()->basePath.'/modules/deal/models/MDealPriceForm.php',
'MDealRecentListModel' => app()->basePath.'/modules/deal/models/MDealRecentListModel.php',
'MDealRedeemSelectForm' => app()->basePath.'/modules/deal/models/MDealRedeemSelectForm.php',
'MDealReviewForm' => app()->basePath.'/modules/deal/models/MDealReviewForm.php',
'MDealSeoForm' => app()->basePath.'/modules/deal/models/MDealSeoForm.php',
'MDealStatusForm' => app()->basePath.'/modules/deal/models/MDealStatusForm.php',
'MDealSubscribeForm' => app()->basePath.'/modules/deal/models/MDealSubscribeForm.php',
'MDealSuggestForm' => app()->basePath.'/modules/deal/models/MDealSuggestForm.php',
'MLocationBackgroundImageForm' => app()->basePath.'/modules/location/models/MLocationBackgroundImageForm.php',
'MLocationForm' => app()->basePath.'/modules/location/models/MLocationForm.php',
'MLocationParamsForm' => app()->basePath.'/modules/location/models/MLocationParamsForm.php',
'MLocationPresetForm' => app()->basePath.'/modules/location/models/MLocationPresetForm.php',
'MPaymentCheckoutForm' => app()->basePath.'/modules/payment/models/MPaymentCheckoutForm.php',
'MPaymentOrderListModel' => app()->basePath.'/modules/payment/models/MPaymentOrderListModel.php',
'MPaymentParamsForm' => app()->basePath.'/modules/payment/models/MPaymentParamsForm.php',
'MPaymentUserModel' => app()->basePath.'/modules/payment/models/MPaymentUserModel.php',
'MTransactionHistory' => app()->basePath.'/modules/payment/models/MTransactionHistory.php',
'MPaypalParamsForm' => app()->basePath.'/modules/payment/modules/paypal/models/MPaypalParamsForm.php',
'UCCExpDate' => app()->basePath.'/modules/payment/modules/ccdirect/components/UCCExpDate.php',
'MCcdirectForm' => app()->basePath.'/modules/payment/modules/ccdirect/models/MCcdirectForm.php',
'MCcdirectParamsForm' => app()->basePath.'/modules/payment/modules/ccdirect/models/MCcdirectParamsForm.php',
'MWireParamsForm' => app()->basePath.'/modules/payment/modules/wire/models/MWireParamsForm.php',
'MSubscriptionCampaignForm' => app()->basePath.'/modules/subscription/models/MSubscriptionCampaignForm.php',
'MSubscriptionParamsForm' => app()->basePath.'/modules/subscription/models/MSubscriptionParamsForm.php',
'MCmsBlockForm' => app()->basePath.'/modules/customize/models/MCmsBlockForm.php',
'MCmsPageForm' => app()->basePath.'/modules/customize/models/MCmsPageForm.php',
'MProfileForm' => app()->basePath.'/modules/user/models/MProfileForm.php',
'MUserAccountForm' => app()->basePath.'/modules/user/models/MUserAccountForm.php',
'MUserAvatarForm' => app()->basePath.'/modules/user/models/MUserAvatarForm.php',
'MUserInstallForm' => app()->basePath.'/modules/user/models/MUserInstallForm.php',
'MUserListModel' => app()->basePath.'/modules/user/models/MUserListModel.php',
'MUserLoginForm' => app()->basePath.'/modules/user/models/MUserLoginForm.php',
'MUserParamsForm' => app()->basePath.'/modules/user/models/MUserParamsForm.php',
'MUserResetForm' => app()->basePath.'/modules/user/models/MUserResetForm.php',
'MUserRestoreForm' => app()->basePath.'/modules/user/models/MUserRestoreForm.php',
'MUserSignupForm' => app()->basePath.'/modules/user/models/MUserSignupForm.php',
'MCompanyForm' => app()->basePath.'/modules/company/models/MCompanyForm.php',
'MCompanyUserForm' => app()->basePath.'/modules/company/models/MCompanyUserForm.php',
'MInstallLoginForm' => app()->basePath.'/modules/install/models/MInstallLoginForm.php',
));

	}
}