<?php
return array(
  'main' => array('label' => 'General Colors', 'items' => array(
    'body.bcg' => array('label' => 'Body Background', 'default' => '#89ac60'),
    'link' => array('label' => 'Link', 'default' => '#0091b5'),
    'link.hover' => array('label' => 'Link (hover)', 'default' => '#00aecb'),
    'button.bcg' => array('label' => 'Button Background', 'default' => '#78d4df',
    	'files' => array(
			'webroot.themes.THEME.views._config.button.png' => 'webroot.themes.THEME.views._config.button-overlay.png',
    		'webroot.themes.THEME.views._config.buttonOnBlack.png' => 'webroot.themes.THEME.views._config.buttonOnBlack-overlay.png',
			'webroot.themes.THEME.views._config.mobileButton.png' => 'webroot.themes.THEME.views._config.mobileButton-overlay.png'
	)),
    'rounded.box.border' => array('label' => 'Rounded Box Border', 'default' => '#5a8e22', 'files' => array('webroot.themes.THEME.views._config.box.png')),
    'rounded.box.highlight' => array('label' => 'Rounded Box Highlight', 'default' => '#ddf2d0'),
    'tabs.selected.bcg' => array('label' => 'Selected Tab Background', 'default' => '#e5e5e5'),
    'tabs.selected.link' => array('label' => 'Selected Tab Text', 'default' => '#000000'),
    'items.header.text' => array('label' => 'Grid List Header Text', 'default' => '#000000'),
    'items.header.bcg' => array('label' => 'Grid List Header Background', 'default' => '#ddf2d0'),
    'items.header.link' => array('label' => 'Grid List Header Link', 'default' => '#666666'),
    'items.even.bcg' => array('label' => 'Grid List Even Row Background', 'default' => '#e9f2e4'),
    'items.odd.bcg' => array('label' => 'Grid List Odd Row Background', 'default' => '#f7f7f7'),
    'items.selected.bcg' => array('label' => 'Grid List Selected Row Background', 'default' => '#BCE774'),
    'items.hover.bcg' => array('label' => 'Grid List Row Background (hover)', 'default' => '#ECFBD4'),
    'email.border' => array('label' => 'Email Border', 'default' => '#e5e5e5'),
  )),
  'header' => array('label' => 'Header Colors', 'items' => array(
  	'header.bcg' => array('label' => 'Header Background', 'default' => '#000000'),
    'header.text' => array('label' => 'Header Text', 'default' => '#9cb77d'),
    'header.link' => array('label' => 'Header Link', 'default' => '#ffffff'),
    'header.border' => array('label' => 'Header Border', 'default' => '#9cb77d'),
    'top.block.bcg' => array('label' => 'Top Slide Box Background', 'default' => '#333333'),
	'top.block.border' => array('label' => 'Top Slide Box Border', 'default' => '#4d4d4d'),
	'top.block.text' => array('label' => 'Top Slide Box Text', 'default' => '#ffffff'),
	'location.item.selected' => array('label' => 'Location Selected Item Background', 'default' => '#666666'),
	'location.country.bcg' => array('label' => 'Location Country Item Background', 'default' => '#404040'),
	'location.country.text' => array('label' => 'Location Country Item Text', 'default' => '#cccccc'),
	'top.menu.link' => array('label' => 'Top Menu Link', 'default' => '#ffffff'),
	'top.menu.arrow' => array('label' => 'Top Menu Arrow', 'default' => '#56a5bc', 'files' => array('webroot.themes.THEME.views._config.arrow.png')),
  )),
  'footer' => array('label' => 'Footer Colors', 'items' => array(
    'footer.bcg' => array('label' => 'Footer Background', 'default' => '#333333'),
	'footer.text' => array('label' => 'Footer Text', 'default' => '#999999'),
	'footer.border' => array('label' => 'Footer Border', 'default' => '#666666'),
	'footer.link' => array('label' => 'Footer Link', 'default' => '#cccccc'),
	'footer.link.hover' => array('label' => 'Footer Link (hover)', 'default' => '#ffffff'),
  )),
  'language' => array('label' => 'Language Dropdown Colors', 'items' => array(
  	'language.text' => array('label' => 'Language Dropdown Text', 'default' => '#cccccc'),
    'language.bcg' => array('label' => 'Language Dropdown Background', 'default' => '#000000'),
    'language.border' => array('label' => 'Language Dropdown Border', 'default' => '#999999'),
    'language.link' => array('label' => 'Language Dropdown Link', 'default' => '#ffffff'),
    'language.selected.bcg' => array('label' => 'Language Dropdown Selected Background', 'default' => '#4d4d4d'),
    'language.selected.text' => array('label' => 'Language Dropdown Selected Text', 'default' => '#cccccc'),
  )),
  'mainmenu' => array('label' => 'Main Menu Colors', 'items' => array(
  	'main.menu.bcg' => array('label' => 'Main Menu Background', 'default' => '#4eacb7'),
    'main.menu.link' => array('label' => 'Main Menu Link', 'default' => '#ffffff'),
    'welcome.text' => array('label' => 'Welcome Text', 'default' => '#000000'),
    'logout.link' => array('label' => 'Logout Link', 'default' => '#ffffff'),
  )),
  'deal' => array('label' => 'Deal Colors', 'items' => array(
    'buy.button.bcg' => array('label' => '"Buy" Button Background', 'default' => '#66bc29'),
    'buy.button.border' => array('label' => '"Buy" Button Border', 'default' => '#d9d9d9'),
    'deal.status.text' => array('label' => 'Deal Status Text', 'default' => '#4a8b1c'),
    'deal.status.border' => array('label' => 'Deal Status Border', 'default' => '#97c78c'),	
    'deal.info.box1.header.bcg' => array('label' => 'Deal Info Box #1 Header Background', 'default' => '#00b8cc'),	
    'deal.info.box1.content.bcg' => array('label' => 'Deal Info Box #1 Content Background', 'default' => '#d0ebf2'),	
    'deal.info.box1.content.border' => array('label' => 'Deal Info Box #1 Content Border', 'default' => '#8cb7c7'),	
    'deal.info.box1.text' => array('label' => 'Deal Info Box #1 Text', 'default' => '#ffffff'),	
    'deal.info.box2.bcg' => array('label' => 'Deal Info Box #2 Background', 'default' => '#ddf2d0'),	
    'deal.info.box2.border' => array('label' => 'Deal Info Box #2 Border', 'default' => '#97c78c'),	
    
  )),
  'mobile' => array('label' => 'Mobile Colors', 'items' => array(
  	'mobile.header.text' => array('label' => 'Mobile Header Text', 'default' => '#ffffff'),
    'mobile.header.bcg' => array('label' => 'Mobile Header Background', 'default' => '#4eacb7'),
    'mobile.header.border' => array('label' => 'Mobile Header Border', 'default' => '#3a7f88'),
  )),
);